In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [36]:
dataset=pd.read_csv("Churn_Modelling.csv")

In [37]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [38]:
X=dataset.iloc[:,3:13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [39]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('one_hot_encoder', OneHotEncoder(), [1,2])],remainder='passthrough')
X= np.array(ct.fit_transform(X), dtype=np.float)

In [40]:
X=X[:,[1,2,3,5,6,7,8,9,10,11,12]]

In [41]:
y=dataset.iloc[:,-1].values

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [43]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [44]:
X_train

array([[-0.5698444 ,  1.74309049,  1.09168714, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -0.91601335, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368,  1.09168714, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368, -0.91601335, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049,  1.09168714, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368,  1.09168714, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [45]:
X_test

array([[ 1.75486502, -0.57369368,  1.09168714, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.5698444 , -0.57369368,  1.09168714, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-0.5698444 ,  1.74309049,  1.09168714, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-0.5698444 ,  1.74309049, -0.91601335, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 1.75486502, -0.57369368, -0.91601335, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 1.75486502, -0.57369368, -0.91601335, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [46]:
import keras

In [47]:
from keras.models import Sequential
#required to initialise the ANN
from keras.layers import Dense
#used to create layers in ANN

In [48]:
classifier=Sequential()

In [49]:
#first hidden layers
classifier.add(Dense(6,input_dim=11,kernel_initializer="uniform",activation="relu"))
#choose number of hidden layer nodes as avg of input layer and output layer
#or use paramteter tuning to select
#input layer nodes(only specify the first time)
#kernel_initializer=uniform to initialise weights close to 0
#activation function

In [50]:
classifier.add(Dense(6,kernel_initializer="uniform",activation="relu"))

In [51]:
classifier.add(Dense(1,kernel_initializer="uniform",activation="sigmoid"))
#if more than 2 categories using softmax function else sigmoid

In [52]:
classifier.compile(optimizer="adam",loss='binary_crossentropy',metrics=['accuracy'])
#binary_crossentropy is for 2 output categories else categorical_crossentropy

In [53]:
classifier.fit(X_train,y_train,epochs=10, batch_size=10)

Epoch 1/10
8000/8000 [==============================] - 2s 249us/step - loss: 0.4797 - accuracy: 0.7962
Epoch 2/10
8000/8000 [==============================] - 2s 234us/step - loss: 0.4209 - accuracy: 0.8089
Epoch 3/10
8000/8000 [==============================] - 2s 241us/step - loss: 0.4137 - accuracy: 0.8151
Epoch 4/10
8000/8000 [==============================] - 2s 213us/step - loss: 0.4068 - accuracy: 0.8185
Epoch 5/10
8000/8000 [==============================] - 2s 220us/step - loss: 0.3929 - accuracy: 0.8314
Epoch 6/10
8000/8000 [==============================] - 2s 254us/step - loss: 0.3688 - accuracy: 0.8481
Epoch 7/10
8000/8000 [==============================] - 2s 215us/step - loss: 0.3540 - accuracy: 0.8575
Epoch 8/10
8000/8000 [==============================] - 2s 220us/step - loss: 0.3493 - accuracy: 0.8596
Epoch 9/10
8000/8000 [==============================] - 2s 254us/step - loss: 0.3479 - accuracy: 0.8571
Epoch 10/10
8000/8000 [==============================] - 2s 230u

In [54]:
y_pred = classifier.predict(X_test)

In [55]:
y_pred=(y_pred>0.5)

In [56]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [57]:
#test set accuracy
scores = classifier.evaluate(X_test,y_test)
print("%s: %.2f%%" % (classifier.metrics_names[1], scores[1]*100))

2000/2000 [==============================] - 0s 26us/step
accuracy: 86.25%


In [58]:

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [59]:
cm

array([[1527,   68],
       [ 207,  198]], dtype=int64)

In [60]:
#new predictions
new_prediction=classifier.predict(sc.transform(np.array([[0,0,600,1,50,3,60000,2,1,1,50000]])))

In [61]:
new_prediction=(new_prediction>0.5)

In [62]:
new_prediction

array([[ True]])

In [63]:
#customer does not leave