In [17]:
#works well on big dataset
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
dataset=pd.read_csv("Churn_Modelling.csv")

In [19]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore  ... HasCrCard IsActiveMember  EstimatedSalary  Exited
0          1    15634602  Hargrave          619  ...         1              1        101348.88       1
1          2    15647311      Hill          608  ...         0              1        112542.58       0
2          3    15619304      Onio          502  ...         1              0        113931.57       1
3          4    15701354      Boni          699  ...         0              0         93826.63       0
4          5    15737888  Mitchell          850  ...         1              1         79084.10       0

[5 rows x 14 columns]

In [20]:
X=dataset.iloc[:,3:13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [21]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('one_hot_encoder', OneHotEncoder(), [1,2])],remainder='passthrough')
X= np.array(ct.fit_transform(X), dtype=np.float)

In [22]:
X=X[:,[1,2,3,5,6,7,8,9,10,11,12]]

In [23]:
y=dataset.iloc[:,-1].values

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [25]:
X_train

array([[0.0000000e+00, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.6383064e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 5.7098000e+04],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.8563076e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.8142987e+05],
       [0.0000000e+00, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.4875016e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1885526e+05]])

In [26]:
X_test

array([[1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.9285267e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.2870210e+05],
       [0.0000000e+00, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 7.5732250e+04],
       ...,
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.4153319e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.1276480e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.9295060e+05]])

In [27]:
from xgboost import XGBClassifier

In [28]:
classifier=XGBClassifier()
classifier.fit(X_train,y_train)

XGBClassifier()

In [29]:
y_pred = classifier.predict(X_test)

In [30]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [31]:
cm

array([[1521,   74],
       [ 197,  208]], dtype=int64)

In [32]:
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,X=X_train,y=y_train,cv=10)

In [33]:
accuracies

array([0.87   , 0.855  , 0.87875, 0.8725 , 0.86   , 0.8525 , 0.865  ,
       0.85   , 0.84875, 0.8725 ])

In [34]:
accuracies.mean()

0.8625

In [35]:
accuracies.std()

0.01017042280340401